gansoi/gansoi

Live.go
main.go
plugins/Notifier.go
plugins/notifiers/slack/Slack.go
web/client.js
web/index.html

This is a work in progress fixing #5.

Contact edit

---

.travis.yml
README.md
checks/Check.go
notify/Contact.go
notify/ContactGroup.go

It's getting more and more difficult to maintain Go 1.6 compatibility.

Require Go 1.8

---

checks/Scheduler.go
eval/Evaluation.go
eval/Evaluator.go
eval/Evaluator_test.go
main.go
notify/Notifier_test.go
plugins/agents/error/Error.go
plugins/agents/error/Error_test.go

This PR avoids database access and IO for evaluating checks allowing for much higher load.

More performance

---

eval/Evaluation.go
eval/Evaluator.go
eval/Evaluator_test.go
web/client.js

This will improve on the the timeline of host based checks.

Host check summary

---

main_test.go

Avoid assuming /dev/shm is present

---

ca/CA.go
ca/CA_test.go
ca/failReader_test.go
ca/helpers.go
ca/helpers_test.go
ca/unknownCurve_test.go

Added tests of a few uncovered core paths.

More tests for the ca package

---

cluster/Core.go
cluster/Info.go
cluster/Info_test.go
main.go
node/HTTPStream.go
node/Node.go
test3.sh

This works as expected for a single node cluster. Not so stable for a multinode cluster yet.

Port to raft protocol v3

---

.dockerignore
Dockerfile
Makefile
README.md
build/variables.go
build/variables_test.go
dockerroot/etc/ssl/certs/.gitignore
dockerroot/etc/ssl/certs/README.md
main.go
main_test.go

This PR adds some version information to the binary and adds a self-contained Docker-build. You can even build Docker images on Windows now :)

Better building

---

plugins/agents/ssh/SSH.go
plugins/agents/ssh/SSH_test.go

Reverts gansoi/gansoi#63
Banner support got pulled in https://github.com/golang/crypto/commit/2509b142fb2b797aa7587dad548f113b2c0f20ce.

Revert "Add support for SSH banner"

---

README.md

Mention our Slack channel in the README

---

Makefile
plugins/agents/tcpport/TCPPort_test.go
plugins/notifiers/email/Email_test.go
plugins/notifiers/email/TestServer_test.go

Avoid IPv6 tests on Travis. Sigh.

Fix travis

---

plugins/agents/ssh/SSH.go
plugins/agents/ssh/SSH_test.go

Let's try again :-)
https://github.com/golang/crypto/commit/9f005a0

Add support for SSH banner

---

Makefile
README.md
docker-compose.yml

This PR will give our Docker support a quick overhaul.

More docker

---

main.go
plugins/agents/smtp/SMTP.go
plugins/agents/smtp/SMTP_test.go

This is a very simple SMTP agent. It doesn't really support anything besides banner retrieval, but it's something :)
Closes #27.

Add simple SMTP agent

---

plugins/agents/http/HTTP.go
plugins/agents/http/HTTP_test.go
plugins/agents/http/writeFailer_test.go
plugins/agents/ping/ICMPService.go
plugins/agents/ping/ICMPService_test.go
plugins/agents/ping/Ping.go
plugins/agents/ping/Ping_test.go
plugins/agents/ping/faker_test.go

More agent tests

---

boltdb/BoltStore.go
boltdb/Snapshot.go
build/variables.go
checks/CheckResult.go
checks/MetaStore.go
checks/Scheduler.go
eval/Evaluation.go
eval/Evaluator.go
main.go
node/Node.go
node/RestAPI_test.go
plugins/agents/filesystem/Filesystem.go
plugins/agents/filesystem/FilesystemInfo.go
plugins/agents/filesystem/Filesystem_test.go
plugins/agents/filesystem/Parser.go
plugins/agents/filesystem/Parser_test.go
plugins/agents/http/writeFailer_test.go

A very simple Storm update is included too.

Inspecode fixes

---

boltdb/BoltStore.go
database/LogEntry.go
database/LogEntry_test.go

It didn't really add any value :-/

Removed error return value from Payload()

---

node/HTTPStream.go
node/HTTPStream_test.go

This test will sometimes fail. This PR hopefully fixes that.

Fix TestStreamEcho()

---

web/client.js

Only load default arguments if it's a new check

---

config/Configuration.go
debian/gansoi.conf
debian/gansoi.yml
debian/rules
dockerroot/etc/gansoi.conf
dockerroot/etc/gansoi.yml
test1.sh
test3.sh

Stage 2. Why this was not included in #86 is a mystery ;)

Ported non-core code to YAML-config

---

web/index.html

This PR should unify the button look and layout across the web interface.

More consistent buttons

---

config/Configuration.go
config/Configuration_test.go
config/testdata/checks.yml
config/testdata/contactgroups.yml
config/testdata/contacts.yml
config/testdata/hosts.yml
main.go
test1.sh

This PR will enable the user to seed the configuration from the YAML condfiguration file.

YAML-based seeding

---

README.md

Real DNS zone updated accordingly.
Fixes #91.

Update test instructions for osx users

---

build/variables.go
plugins/agents/http/HTTP.go
plugins/agents/ping/ICMPPayload.go
plugins/agents/ssh/SSH.go
transports/ssh/SSH.go

Properly identify ourselves when contacting other hosts.

Identify ourselves

---

boltdb/BoltStore.go
boltdb/Snapshot.go

This PR will update Gansoi to match the Storm bbolt-import-path.
Please see asdine/storm#231

Use import bbolt import from go.etcd.io

---

plugins/agents/mysql/Mysql_test.go

Implement HandleOtherCommand() in mysql mock

---

.travis.yml
ca/failReader_test.go

Re-apply Travis Go 1.10 workaround

---

main.go

As suggested by `rsc.io/letsencrypt` this PR will enable Gansoi to use `golang.org/x/crypto/acme/autocert` for LetsEncrypt certificates.

Replaced deprecated letsencrypt dependency with autocert

---

web/client.js
web/g-collection.js
web/index.html
web/style.css

Because vis.js is mostly abandoned...

Ported web client to timeline.js
